### ISSUE TITLE
Visual Studio App Center Android app no longer available in the Google Play store

### ISSUE THREAD

**Issue by ferdicus** [microsoft/appcenter#2174]
We noticed, that the Visual Studio App Center Android app seems to no longer be available within the Google Play Store?
Instead when searching for it another app shows up: 
https://play.google.com/store/apps/details?id=com.ahmetkocu.appcenterclient

Which clearly does not seem to be created by Microsoft. 

The previous link to the official App Center App, leads to nowhere:
https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp

This seems all very fishy - is there an official statement about this anywhere?
Did something change? 

Thanks in advance
And sorry if this is a duplicate or a known issue - this hit us by surprise...

EDIT: 
found this lonely tweet about this: https://twitter.com/jasper_slot/status/1381964491328421889

**Comment by bobekos** [comment]
Any news to this?

**Comment by ferdicus** [comment]
Our company sent a support mail to MS about this and they nonchalantly explained, that 
> Due to Google Play policies, the Visual Studio App Center app is no longer available in the Google Play store and there are no current plans to bring the app back to the Google Play store.

Furthermore they mentioned, that the same functionality is available through the browser though...

The things I don't like about this whole thing:
* no notification of users that this app is no longer available
* marketplace confusion

The later point is more severe if you ask me, because there is already another application which people might think is the same app with a new coat of paint (and affiliated with MS ) [App Center Client](https://play.google.com/store/apps/details?id=com.ahmetkocu.appcenterclient&hl=en&gl=US). 

So people just download that and put in their credentials... 

not cool

**Comment by bobekos** [comment]
oh man...thanks for the news microsoft ...anyway good to know that thanks for the quick response @ferdicus

**Comment by eman1986** [comment]
The app was super limited in functionality anyway, it's for the best.

**Comment by bluearth** [comment]
[This is](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android) the closest to official announcement I can find regarding this matter. Can't find anything else regarding this course of event anywhere. No email, No tweets, nothing.

**Comment by ferdicus** [comment]
> [This is](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android) the closest to official announcement I can find regarding this matter. Can't find anything else regarding this course of event anywhere. No email, No tweets, nothing.

Which happened [a day after](https://github.com/MicrosoftDocs/appcenter-docs/commit/cf8e38a47d99d47e519ec6ddde8c396677042a7e#diff-a7a7918e84d595b7ff6812809db78cadc83a8733ddf05548b9c5efb99412dbb2) my [last comment](https://github.com/microsoft/appcenter/issues/2174#issuecomment-831231589)....

**Comment by wisdeom** [comment]
Hi all, so sorry about any inconvenience caused and the lack of response here. App Center Android app served our customers well and we're very sad to let it go. Unfortunately, our hands were pretty much tied in this situation along with other changes we had to make for [Distribute SDK](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) last year. About misrepresenting Microsoft App Center client apps, we're working on reaching out to them and taking the necessary action. 

Last but not least, we could have done a better job in communicating this change, and that's on us. Appreciate your patience with us and your feedback. It means a lot.

**Comment by Solid-Metal** [comment]
so...how do we get the app now?, we hire new QA whos direly need it, seems i can't find any link regarding manual download of the apk from anywhere

**Comment by eman1986** [comment]
If you just visit the website your QA can install the app from their test devices, that's how my QA team does it.

**Comment by CBuntrock** [comment]
> 
> 
> Hi all, so sorry about any inconvenience caused and the lack of response here. App Center Android app served our customers well and we're very sad to let it go. Unfortunately, our hands were pretty much tied in this situation along with other changes we had to make for [Distribute SDK](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) last year. About misrepresenting Microsoft App Center client apps, we're working on reaching out to them and taking the necessary action.
> 
> Last but not least, we could have done a better job in communicating this change, and that's on us. Appreciate your patience with us and your feedback. It means a lot.

Thanks anyway for the update here. Please keep in mind that there are big enterprise clients using this. It really brings partners also into problematic situations...
Best,
Chris

**Comment by strindhaug** [comment]
Someone should fix the page that the "Sign in" button in the app sends you to so it doesnt redirect you to some `ms-actesterapp://login...` url that doesn't work. This should instead send you to a page saying the app is discontinued or something like that.

**Comment by GokhanArik** [comment]
When I contacted support they told me to use https://install.appcenter.ms, going forward this will be the one they will maintain.

**Comment by ferdicus** [comment]
> When I contacted support they told me to use https://install.appcenter.ms, going forward this will be the one they will maintain.

Yes, that is understood - it's clear, that there is an alternative.  
The issue at hand was, that we have clients, all of whom where using the app center client app on their devices.  
Now from one day to the other the app disappears from the play store and now the installed instances stopped working PLUS the app store presence got replaced with some dubious app that pretends to be the same.  

It's all just very unfortunate and unprofessional - something you'd expect from a small startup, definitely not MS.

**Comment by jayanthrbharadwaj** [comment]
@ferdicus @GokhanArik 
Hi Guys, my friend is developing AppCenter app. Do you think it would be a good idea if it is available on playstore?


https://twitter.com/bharadwauj/status/1416816648443482112

**Comment by jayanthrbharadwaj** [comment]
> Hi all, so sorry about any inconvenience caused and the lack of response here. App Center Android app served our customers well and we're very sad to let it go. Unfortunately, our hands were pretty much tied in this situation along with other changes we had to make for [Distribute SDK](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) last year. About misrepresenting Microsoft App Center client apps, we're working on reaching out to them and taking the necessary action.
> 
> Last but not least, we could have done a better job in communicating this change, and that's on us. Appreciate your patience with us and your feedback. It means a lot.

Would it be a problem if a third party developed using webview of appcenter and launched it in playstore? the app launches a webview

**Comment by ferdicus** [comment]
@jayanthrbharadwaj - this was the whole impetus of why I also opened this issue ticket to begin with... a third party app filling the void that MS departure created...

Why would anyone use a third party app with something that is this sensitive?  
Do you think I'd send my login and password through your friends AppCenter app? 

🙄

**Comment by zfedoran** [comment]
I'm really disappointed in Microsoft here... the entire time they had been announcing the shutdown of the `HockeyApp` we were under the impression that they meant the old version of the app which was legitimately named "HockeyApp". Now we're finding out that they really meant the `Visual Studio App Center` app. 

We've got some big and angry clients who now want us to dump Microsoft products on principal alone. Good job guys.

**Comment by jmkolbe** [comment]
That's indeed unfortunate. I get that Google policies make life difficult sometimes, and acknowledge pulling the plug sometimes is the sensible option.

On the other hand, having testers use the browser depends on them allowing the browser to install apps from unknown sources. A simple standalone webview app distributed by Microsoft might mitigate that issue at a perhaps not too high cost.

**Comment by brzezinol** [comment]
I fixed this problem with conditional package reference.

`<Choose>
    <When Condition=" '$(Configuration)' != 'GooglePlay' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" />
      </ItemGroup>
    </When>
    <When Condition=" '$(Configuration)' == 'GooglePlay' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.AppCenter.DistributePlay" Version="3.4.3" />
      </ItemGroup>
    </When>
  </Choose>`

but due to bug in VS finally code looks like below 
`<Choose>
    <When Condition=" '$(Configuration)' != 'GooglePlay' ">
      <ItemGroup>
        <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" />
      </ItemGroup>
    </When>
  </Choose>`

Every time I build GooglePlay build, i check final aab file for existing Distribute assembly. One time for some reason Distribute lib was added to aab file and Google blocked my app. But successfully I wrote to helpdesk and app was resumed.

**Comment by ferdicus** [comment]
> 

and that is relevant to this issue how @brzezinol ???

**Comment by brzezinol** [comment]
> 

Wrong ticket my fault.

**Comment by brzezinol** [comment]
> > I fixed this problem with conditional package reference.
> > `<Choose> <When Condition=" '$(Configuration)' != 'GooglePlay' "> <ItemGroup> <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" /> </ItemGroup> </When> <When Condition=" '$(Configuration)' == 'GooglePlay' "> <ItemGroup> <PackageReference Include="Microsoft.AppCenter.DistributePlay" Version="3.4.3" /> </ItemGroup> </When> </Choose>`
> > but due to bug in VS finally code looks like below `<Choose> <When Condition=" '$(Configuration)' != 'GooglePlay' "> <ItemGroup> <PackageReference Include="Microsoft.AppCenter.Distribute" Version="3.4.3" /> </ItemGroup> </When> </Choose>`
> > Every time I build GooglePlay build, i check final aab file for existing Distribute assembly. One time for some reason Distribute lib was added to aab file and Google blocked my app. But successfully I wrote to helpdesk and app was resumed.
> 
> and that is relevant to this issue how @brzezinol ???

Wrong ticket my fault.

**Comment by aodegov** [comment]
still no luck with app center into the Google Play Store...
any news MS team?

**Comment by AnastasiaKubova** [comment]
Hi there! Unfortunately, Visual Studio App Center app is no longer available in the Google Play store due to Google Play restrictions but you can use the App Center install portal instead ([please see](https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android)).
Duplicate #2229

**Comment by brzezinol** [comment]
@ferdicus Is the only reason why Visual Studio App Center app is no longer available in the Google Play store is that, code uses in-app AppCenter distribution?

**Comment by ferdicus** [comment]
dude, I'm not affiliated with MS :)

**Comment by AnastasiaKubova** [comment]
Hi, @brzezinol ! Yes, Google Play detects in-app update code as malicious. There are no current plans to bring the app back to the Google Play store due to their policies. You can use App Center to install the portal instead.

**Comment by brzezinol** [comment]
@ferdicus I notify you, because you wrote that my comment is not relevant in this issue. I think yes, because I had the same problem with Google Play and in-app updates and I bring my app back to store. But i'm sory if I bothering you too much.

@AnastasiaKubova So even if you remove from GooglePlay config your in-app updates, you have no plans to bring app back to google play store? I asking because it is possible, and if you have no Distribute package in your app, Google allows reinstantiate app in store.

**Comment by aodegov** [comment]
@AnastasiaKubova , sorry, is it possible to work on this issue from MS side and resolve this?

**Comment by wisdeom** [comment]
@brzezinol Hi again, Google Play Store considers this as malicious. Any 3rd party apps in Google Store will be eventually taken down. Apologies for the inconvenience. I'm doing my best in reaching out to any apps misrepresenting App Center service. Sorry for the confusion.

**Comment by brzezinol** [comment]
Is app available to download from ms app center?

**Comment by ferdicus** [comment]
> @brzezinol Hi again, Google Play Store considers this as malicious. Any 3rd party apps in Google Store will be eventually taken down. Apologies for the inconvenience. I'm doing my best in reaching out to any apps misrepresenting App Center service. Sorry for the confusion.

translation: Visual Studio App Center Android App will never ever be on the Play Store again

Just to manage expectations....
