### ISSUE TITLE
app.Repl(); does not work with  Xamarin.UITest version 4.0.1-4.1.0 with the error of "This is not the real repl - this is just a placeholder."

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2498]
app.Repl(); does not work with  Xamarin.UITest version 4.0.1-4.1.0 with the error of:
"This is not the real repl - this is just a placeholder."
This issue is new to Xamarin.UITest version 4.0.1 and does not happen on the previous versions. I am not sure what is causing the issue but any workaround is greatly appreciated. This issue stops the ability to use app.Repl(); is all forms and the feature is completely broken, if this is a bug on your end a quick release to fix the issue would be most necessary since the importance of the feature that is down.
Thank you for your help in advance!

Screenshot of the issue:

![Screen Shot 2022-12-05 at 12 02 31 PM](https://user-images.githubusercontent.com/6087936/205721711-64812401-9ba6-486c-9772-a2f48645d187.png)

**Comment by MrAusnadian** [comment]
LOL. Microsoft really need to improve their QA

**Comment by IlyaBausovAkvelon** [comment]
Hi all. This is the know issue. It has became broken after .Net 6 support. We working on fix.

**Comment by Moshex** [comment]
@IlyaBausovAkvelon Thank you for looking into this!

**Comment by IlyaBausovAkvelon** [comment]
Hi all.
@Moshex and @MrAusnadian have you ever tried to use native VS debugger?

**Comment by Moshex** [comment]
> Hi all. @Moshex and @MrAusnadian have you ever tried to use native VS debugger?

as a replacement for app.Repl()? for would the debugger be of any use?

**Comment by IlyaBausovAkvelon** [comment]
You can run statements here like we do this in REPL. How do you use REPL?

**Comment by Moshex** [comment]
I use REPL to simulate automation actions to see if they work, validate elements, and use the command "tree" to give me an idea of a full-page read of elements.  this is one of the most useful tools when writing tests. I know in a debug window you can inject code while the test is running but that is only part of the picture that REPL handles.

**Comment by IlyaBausovAkvelon** [comment]
@Moshex I am working on rewriting REPL right now. There were issues more than just "Placeholder" message. It just don't work anymore on .NET Framework 4.6.2 and .NET 6. We need to rewrite it first.
Please consider using the Immediate window of the debugger for now as a workaround.

**Comment by sjavashev** [comment]
@IlyaBausovAkvelon can you please elaborate a bit?

Do you mean using edit-and-continue to enter commands like the following directly in the code and then examine the result with a debugger's quick watch or on the screen?
```
			var list = app.Query(x => x.All());
			app.Flash(x => x.Text("Label Name"));
```

(Maybe this is already known, but I have trouble running these from the Immediate window - I get "...Evaluation of native methods in this context is not supported.")

And also, if this is the way, can you suggest something to list the current on-screen widget hierarchy as a replacement for the Repl's "tree" command?

**Comment by IlyaBausovAkvelon** [comment]
@sjavashev You can try to use _app.Print.Tree(). It's not working like REPL in the edit-and-continue screen but you can put it in the test code. It will print everything in test logs.

**Comment by Moshex** [comment]
> @sjavashev You can try to use _app.Print.Tree(). It's not working like REPL in the edit-and-continue screen but you can put it in the test code. It will print everything in test logs.

@IlyaBausovAkvelon 

one big downfall difference with the immediate window is that when you do a flash or query of an element it does not return the elements' information at all see below:

```
app.Query("Yes")
{Xamarin.UITest.Queries.AppResult[1]}
	[0]: {Xamarin.UITest.Queries.AppResult}
app.Flash("Yes")
{Xamarin.UITest.Queries.AppResult[1]}
	[0]: {Xamarin.UITest.Queries.AppResult}
```

Also, I have not been able to get any resemblance of the function "tree" to work in the immediate window. Please fix REPL when you can, thank you!

**Comment by MikhailSuendukov** [comment]
Hi @Moshex We keep working on it.

**Comment by EllaVader** [comment]
@IlyaBausovAkvelon 
Do you have a time frame when you expect there to be a fix for this?  Is anyone actively working on it?

> @Moshex I am working on rewriting REPL right now. There were issues more than just "Placeholder" message. It just don't work anymore on .NET Framework 4.6.2 and .NET 6. We need to rewrite it first. Please consider using the Immediate window of the debugger for now as a workaround.

**Comment by IlyaBausovAkvelon** [comment]
@EllaVader We are working on fixing REPL. Please wait for an official release.

**Comment by aseigneur** [comment]
Hi, on my side the REPL of Xamarin.UITest version 4.1.1 works after adding SQLitePCLRaw.core dll.

**Comment by EllaVader** [comment]
> Hi, on my side the REPL of Xamarin.UITest version 4.1.1 works after adding SQLitePCLRaw.core dll.

Yes I am seeing that version 4.1.1 came out with apparent fix to Repl tool, however getting this exception 

`Could not load type of field 'Microsoft.CodeAnalysis.SQLite.Interop.SafeSqliteBlobHandle:_wrapper' (0) due to: Could not load file or assembly 'SQLitePCLRaw.core, Version=2.0.7.1395, Culture=neutral, PublicKeyToken=1488e028ca7ab535' or one of its dependencies.`

How exactly did you add SQLitePCLRaw.core dll to get it to work?

**Comment by Moshex** [comment]
@EllaVader Thank you for your input once adding sqlite-net-pcl to my project I was able to get the repl to work

@IlyaBausovAkvelon  I think per @EllaVader  sugestion we can call this issue closed once Xamarin.UITest adds sqlite-net-pcl as a dependency that is what makes the repl work. I also want to point out that the repl's autocomplete appears to be broken. if you use the "tree" command then do "app." no auto-complete options display. Also if you do just app. without doing the "tree" command and press "tab" then the auto-fill brakes removing the "app.". For example, if you do "app.Falsh()" and you use the auto-complete it will just display "Flash" without the correct syntax.  I really hope this can get fixed soon!

**Comment by EllaVader** [comment]
@Moshex I definitely think they should fix the autocomplete too. Hopefully by us reporting the issues found with the latest version they will fix those too and provide an update

**Comment by IlyaBausovAkvelon** [comment]
@Moshex @EllaVader @aseigneur Thank you for reporting it. We will create issues for autocomplete and adding missed assembly.

**Comment by Moshex** [comment]
@IlyaBausovAkvelon  @EllaVader @aseigneur 
I have tested Xamarin.UITest version 4.1.2 and it appears to have added the needed dependency for repl and it working for me as expected. You can see the details here of the version https://www.nuget.org/packages/Xamarin.UITest/ . The issue with the auto-complete is still present in this version.

**Comment by vvechkanov** [comment]
@Moshex 
Thank you for checking version 4.1.2 so fast. We are glad that everything works as expected now. 
About autocomplete issue, as @IlyaBausovAkvelon wrote we already have a ticket for that on our board.

**Comment by EllaVader** [comment]
> @Moshex Thank you for checking version 4.1.2 so fast. We are glad that everything works as expected now. About autocomplete issue, as  @IlyaBausovAkvelon wrote we already have a ticket for that on our board.
@IlyaBausovAkvelon 
Is the autocomplete issue logged somewhere here in github issues? If so can you provide the issue link here so I can follow it?  I'm not finding it when searching for it.  Thanks

**Comment by corradolab** [comment]
Still not working in 4.1.3. app.Repl() does nothing. No error reported but Repl does not show up. I'm using Net 7.

**Comment by Blackhawk50000** [comment]
please... fix this..... 
is there a workaround?

**Comment by IlyaBausovAkvelon** [comment]
@Blackhawk50000, @corradolab Hi!
Could you please provide more details?

**Comment by christian26A** [comment]
Hi, @IlyaBausovAkvelon repl's autocomplete still not working. Just tried on the latest UITest version 4.2.0. This needs to be fixed very soon.

**Comment by Moshex** [comment]
> @EllaVader Thank you for your input once adding sqlite-net-pcl to my project I was able to get the repl to work
> 
> @IlyaBausovAkvelon I think per @EllaVader sugestion we can call this issue closed once Xamarin.UITest adds sqlite-net-pcl as a dependency that is what makes the repl work. I also want to point out that the repl's autocomplete appears to be broken. if you use the "tree" command then do "app." no auto-complete options display. Also if you do just app. without doing the "tree" command and press "tab" then the auto-fill breaks removing the "app.". For example, if you do "app.Falsh()" and you use the auto-complete it will just display "Flash" without the correct syntax. I really hope this can get fixed soon!

The issue mentioned here is still broken in Xamarin.UITest version 4.2.0
