### ISSUE TITLE
IOS NativeAOT trim analysis warnings

### ISSUE THREAD

**Issue by charlesroddie** [microsoft/appcenter#2586]
Build an IOS app with AppCenter using NativeAOT on dotnet8 rc1. There are the following warnings:

```
ILC : Trim analysis warning IL2026: Microsoft.AppCenter.Crashes.Crashes.GenerateStackFrames(Exception): Using member 'System.Diagnostics.StackFrame.GetMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
ILC : Trim analysis warning IL2026: Microsoft.AppCenter.Crashes.Crashes.GenerateStackFrames(Exception): Using member 'System.Diagnostics.StackFrame.GetMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
ILC : Trim analysis warning IL2026: Microsoft.AppCenter.Crashes.Crashes.GenerateStackFrames(Exception): Using member 'System.Diagnostics.StackFrame.GetMethod()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Metadata for the method might be incomplete or removed.
ILC : Trim analysis warning IL2070: Microsoft.AppCenter.AppCenter.GetBindingType(Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The parameter '#0' of method 'Microsoft.AppCenter.AppCenter.GetBindingType(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```

**Comment by DmitriyKirakosyan** [comment]
Hi @charlesroddie , this seems to be a duplicate of https://github.com/microsoft/appcenter/issues/2570. It was confirmed as an dotnet/xamarin issue, see https://github.com/xamarin/xamarin-macios/issues/18736 and they have already fixed it just recently.

**Comment by charlesroddie** [comment]
These are current trim issues on RC1. The previous ones were fixed in RC1.

**Comment by DmitriyKirakosyan** [comment]
Anyway, I'm going to close it as a duplicate of #2570 and not an SDK issue. Let me know if you have additional questions.

**Comment by charlesroddie** [comment]
We are still getting these warnings. The warnings clearly come from Microsoft.AppCenter and will allow you to identify the problematic lines of code in your codebase.

**Comment by DmitriyKirakosyan** [comment]
@charlesroddie , [the issue](https://github.com/xamarin/xamarin-macios/issues/18736) is closed as fixed on the dotnet side, please make sure you are using the proper dotnet version.

In case updating dotnet doesn't resolve your problem, it would be best to seek further assistance by posting your query in this [thread](https://github.com/xamarin/xamarin-macios/issues/18736).

**Comment by rolfbjarne** [comment]
@DmitriyKirakosyan This is not an issue in xamarin/xamarin-macios (aka a duplicate of #2570), it's an issue in AppCenter.

Specifically here:

https://github.com/microsoft/appcenter-sdk-dotnet/blob/43de9063bee90c9329a8197d586033d08fbad86b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Apple/Crashes.cs#L185

https://github.com/microsoft/appcenter-sdk-dotnet/blob/43de9063bee90c9329a8197d586033d08fbad86b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Apple/Crashes.cs#L189

https://github.com/microsoft/appcenter-sdk-dotnet/blob/43de9063bee90c9329a8197d586033d08fbad86b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Apple/Crashes.cs#L190

https://github.com/microsoft/appcenter-sdk-dotnet/blob/43de9063bee90c9329a8197d586033d08fbad86b/SDK/AppCenter/Microsoft.AppCenter.Apple/AppCenter.cs#L200

**Comment by MikhailSuendukov** [comment]
Hello and sorry for the long delay. 
I've been unable to reproduce the warnings you've mentioned. I've tested with both the 8.0.201 and 8.0.100-rc.1.23463.5 versions of .NET, but without success. 
Also, if you could send over a small demo app where the warnings are reproducing, along with repro steps, the .NET version you're using, and your OS, that would help us investigate it deeply.

**Comment by DmitriyKirakosyan** [comment]
Closing. Please reopen if you are still interested.
