### ISSUE TITLE
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

### ISSUE THREAD

**Issue by KthProg** [microsoft/appcenter#829]
**What App Center service does this affect?**
Xamarin.UITest

**Describe the bug**
ExitCode is given as 64. The test output shows that xcodebuild failed with the error "option Destination requires at least one parameter of the form 'key=value'". This suggests that the xcode build destination syntax is incorrect (do I need a specific version of xcodebuild perhaps?)

**To Reproduce**
Try to connect to an iOS simulator by id, with a .app file given to install.
NUnit 3.12.0
Xamarin.UITest 3.03-dev1
iOS 12.4 simulator
XCode 10.3
Build version 10G8

**Expected behavior**
The tests run.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.5

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus Simulator
 - OS: iOS 12.4

**Comment by KthProg** [comment]
Also possible that this is the timing issue in the release notes for Xamarin.UITest? https://www.nuget.org/packages/Xamarin.UITest/3.0.3-dev1

**Comment by nielscup** [comment]
Same issue here, unable to run UITests on iOS simulator. VS2019, Xcode 10.2 and 10.3. It worked fine before upgrading to VS2019 with Xcode 10.1

**Comment by akamud** [comment]
Same problem here.

**Comment by Oddj0b** [comment]
We have a fix available in the latest dev release of Xamarin.UITest, you can get it through your Nuget channels.

**Comment by Agitto** [comment]
Seems like the issue is successfully fixed in 3.0.4-dev1 but only for libraries that target .net45. It is still possible to reproduce the issue by referencing Xamarin.UITest 3.0.4-dev1 from netcoreapp2.0. Can it be possible that libraries from Nuget package for 'net45' and 'portable-net45+win8+wp8' were built from different sources?

**Comment by KthProg** [comment]
@Agitto I really hope that's not the case since I'm using .NET Core 2.0 :(

**Comment by KthProg** [comment]
So I noticed when I installed the new package from Nuget, the project was actually rewritten to use 3.0.3 instead???

**Comment by KthProg** [comment]
@Oddj0b I'm still seeing this issue although it is on a .NET Core 2.0 unit test application as @Agitto  mentioned.

**Comment by Oddj0b** [comment]
@KthProg seems like we didn't get rid of the bug. I will talk with the engineers.

**Comment by Agitto** [comment]
@Oddj0b Any news on this?

**Comment by Oddj0b** [comment]
@Agitto Is this still an issue with Xamarin.UITest 3.0.4?

**Comment by Moshex** [comment]
I am on Xamarin.UITest 3.0.4 and I am getting:
`Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Unable to verify app installation state

ExitCode: 134

  Reason: no suitable image found.  Did find:
  Referenced from: /var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/iOSDeviceManager
	/private/var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore: code signature invalid for '/private/var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore'
	/private/var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore: stat() failed with errno=1
dyld: Library not loaded: @rpath/FBControlCore.framework/Versions/A/FBControlCore`

is there anything I need to do to stop getting the error?

**Comment by manikantasanisetty** [comment]
I downgraded Xamarin.UITest package to 3.0.3 and started working for me.

**Comment by Moshex** [comment]
@manikantasanisetty  Your suggestion worked, thank you so much! is  Xamarin.UITest package to 3.0.4 broken and will it be fixed in Xamarin.UITest package to 3.0.5?

**Comment by jbachelor** [comment]
@Moshex and @manikantasanisetty - Thanks so much. I'm getting this same issue:

```
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Unable to verify app installation state

ExitCode: 134

  Reason: no suitable image found.  Did find:
  Referenced from: /var/folders/2r/mzzw3ntn7vx0g_5b7sb3w2rc0000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/iOSDeviceManager
	/private/var/folders/2r/mzzw3ntn7vx0g_5b7sb3w2rc0000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore: code signature invalid for '/private/var/folders/2r/mzzw3ntn7vx0g_5b7sb3w2rc0000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore'
	/private/var/folders/2r/mzzw3ntn7vx0g_5b7sb3w2rc0000gn/T/xdb/DeviceAgent.iOS.Dependencies/0a3ddc92d1ddf25e2059c72229db762c/bin/../Frameworks/FBControlCore.framework/Versions/A/FBControlCore: stat() failed with errno=1
dyld: Library not loaded: @rpath/FBControlCore.framework/Versions/A/FBControlCore
Stack trace:
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, System.Boolean clearAppData) [0x001e2] in <d5bd61e036ae46c2b2f03bfcebbe2f0a>:0 
  at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Http.HttpClient httpClient, Xamarin.UITest.TestCloud.TestCloudiOSAppConfiguration testCloudAppConfiguration, Xamarin.UITest.Shared.Http.HttpClient testCloudWsClient, Xamarin.UITest.Shared.Http.HttpClient xtcServicesClient, System.Boolean testCloudUseDeviceAgent) [0x00068] in <d5bd61e036ae46c2b2f03bfcebbe2f0a>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration, Xamarin.UITest.Shared.Execution.IExecutor executor) [0x0026f] in <d5bd61e036ae46c2b2f03bfcebbe2f0a>:0 
  at Xamarin.UITest.iOS.iOSApp..ctor (Xamarin.UITest.Configuration.IiOSAppConfiguration appConfiguration) [0x00000] in <d5bd61e036ae46c2b2f03bfcebbe2f0a>:0 
  at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp (Xamarin.UITest.Configuration.AppDataMode appDataMode) [0x00017] in <d5bd61e036ae46c2b2f03bfcebbe2f0a>:0 
  at SweetApp.UITests.AppManager.StartApp () [0x00064] in /Users/Shared/src/SweetAppMobile/SweetApp.UITests/AppManager.cs:56 
  at SweetApp.UITests.BaseTestFixture.BeforeEachTest () [0x00021] in /Users/Shared/src/SweetAppMobile/SweetApp.UITests/BaseTestFixture.cs:25 
  at SweetApp.UITests.Tests.PlusButtonTests.BeforeEachTest () [0x00001] in /Users/Shared/src/SweetAppMobile/SweetApp.UITests/Tests/PlusButtonTests.cs:16 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395
``` 

Downgrading to Xamarin.UITest 3.0.3 seems to fix the issue. Should this be reported in a new issue, since the original issue posted here is about a different error?

> ExitCode is given as 64. The test output shows that xcodebuild failed with the error "option Destination requires at least one parameter of the form 'key=value'".

**Comment by Moshex** [comment]
@jbachelor and @manikantasanisetty , I opened a new issue here: https://github.com/microsoft/appcenter/issues/1477 feel free to add to it as needed.

**Comment by jonstoneman** [comment]
UITest 3.0.5 has been released. Could you all test with that and let us know whether you are still experiencing any problems please?

**Comment by lukashaertel** [comment]
@jonstoneman I experienced the bug with 3.0.4, updated to 3.0.5 and now the bug does not appear anymore.

**Comment by pontusntengnas** [comment]
3.0.5 seem to fix the issue for me

**Comment by imatviienkoomcinc** [comment]
Hi Guys, I have faced a similar issue
`Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

ExitCode: 64`

with such configuration: 
NUnit 3.12.0
Xamarin.UITest 3.0.5(same issue with 3.0.6. dev)
iOS 13.3 simulator
XCode 11.3
.netcore 3.0

When I have the same configuration but with NET framework 7.7.2, all works well. 

Does Xamarin.UITest support .netcore 3.0?

**Comment by imatviienkoomcinc** [comment]
Hi guys, I got : 
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent
ExitCode: 64
on the latest version : 3.0.5 (same for 3.0.6.dev) it is only reproduce only with .net core 3.0. It works fine with net472.

**Comment by nielscup** [comment]
Xamarin.UITest 3.0.5 solves this issue for me.

**Comment by imatviienkoomcinc** [comment]
@nielscup Hi man, Are you using .net core 3.0? Here is code I have used in my tests: 
`if (Platform == Platform.iOS)
            {
                app = ConfigureApp
                    .iOS
                    .AppBundle ("../../../iOS/bin/iPhoneSimulator/Debug/test-tests.iOS.app")
                    .DeviceIdentifier("B3708E9D-6781-490F-B28C-EA73C0206EF4")
                    .StartApp();
            }`

After the launch, I got the error I mentioned above. I try 3.0.5, it did not help. Maybe you can suggest some additional things for investigations.

**Comment by nielscup** [comment]
Hi, we use shared lib, no .netcore, and the following config:
`ConfigureApp
                .iOS
                .Debug()
                .InstalledApp(iOSBundleId)
                .StartApp(AppDataMode.DoNotClear);`

Where iOSBundleId is `domain.com.yourappname`.

Also clear your bin and obj folders and uninstall your app after updating config. Then build and deploy your app and try to run your UITest a second time when the first time does not work because sometimes it fails the first time, but works the second (I think this is another UITest issue).

Hope it helps.

**Comment by jonstoneman** [comment]
@imatviienkoomcinc I'm afraid UITest does not support .net core

**Comment by imatviienkoomcinc** [comment]
@jonstoneman Thanks a lot for the clarification. Are you going to support it in the near future? (By the way, it is perfectly work for Android, that's why I had this concern). Thanks in advance for the answer, I really struggle with searching for answer.

**Comment by jonstoneman** [comment]
@imatviienkoomcinc The work to add .net core support has not yet been scheduled.

**Comment by tarunmittal2012** [comment]
I am using nunit 2.6.4 xamarin ui test 3.0.5,
VS 2019 mac os Catalina, iOS 13getting exception failed to install device agent.
I tried with 3.0.7  as well still get this issue.

**Comment by sreeneshspai** [comment]
@tarunmittal2012 Did you get this fixed?

**Comment by chrisweihu** [comment]
why is this ticket marked as closed. it is clearly still occuring and not fixed.
